Essiga/fhvhotel

- .idea/vcs.xml
- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/CheckInServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/ViewBookingServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/api/CheckInService.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/api/ViewBookingService.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/api/BookingRepository.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/BookingRepositoryImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingController.java
- hotelsoftware/src/main/resources/data.sql
- hotelsoftware/src/main/resources/templates/dashboard.html
> Todays Checkouts done

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/CheckInServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/api/CheckInService.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/api/BookingRepository.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/Booking.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/Room.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/BookingRepositoryImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingController.java
- hotelsoftware/src/main/resources/HibernateBooking.hbm.xml
- hotelsoftware/src/main/resources/HibernateRoom.hbm.xml
- hotelsoftware/src/main/resources/data.sql
- hotelsoftware/src/main/resources/data.sql1
- hotelsoftware/src/main/resources/templates/dashboard.html
SQL Statements and checkedIn Status | find by id
> checkIn Backend

- .idea/modules.xml
- .idea/workspace.xml
- hotelsoftware/src/main/resources/templates/bookingSummary.html
- hotelsoftware/src/main/resources/templates/checkInGuestOverview.html
- hotelsoftware/src/main/resources/templates/chooseRoom.html
- hotelsoftware/src/main/resources/templates/createCustomer.html
- hotelsoftware/src/main/resources/templates/dashboard.html
> UI Size adjustments

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/dto/BookingDTO.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/BookingRepositoryImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/RoomRepositoryImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/form/BookingForm.java
now using query.setPrameter(), this way we can directly use a UUID without converting it to a string beforehand.
> fixed sql queries

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/CheckInServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/CreateBookingServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/dto/BookingDTO.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/Booking.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/RoomCategory.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingController.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/form/BookingForm.java
- hotelsoftware/src/main/resources/HibernateBooking.hbm.xml
- hotelsoftware/src/main/resources/templates/bookingSummary.html
- hotelsoftware/src/main/resources/templates/checkInGuestOverview.html
- hotelsoftware/src/main/resources/templates/chooseRoom.html
- hotelsoftware/src/main/resources/templates/extraService.html
changed luxus to superior and stay duration to length of stay
> english corrections

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/Invoice.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/Room.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/valueobjects/Address.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/valueobjects/GuestData.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/CheckOutServiceTest.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/CreateInvoiceServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewInvoiceServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/BookingTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/InvoiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/RoomCategoryTests.java
> Booking_Test

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingController.java
- hotelsoftware/src/main/resources/templates/bookingSummary.html
- hotelsoftware/src/main/resources/templates/checkInGuestOverview.html
- hotelsoftware/src/main/resources/templates/checkOutGuestOverview.html
- hotelsoftware/src/main/resources/templates/chooseRoom.html
- hotelsoftware/src/main/resources/templates/createGuest.html
- hotelsoftware/src/main/resources/templates/createInvoice.html
- fixed back buttons (CheckInGuestOverview.html, CheckOutGuestOverview.html, createGuest.html, chooseRoom.html)
- fixed input validation error for createGuest.html
- confirm button aligned right (bookingSummary.html)
- company Name + Voucher Code in createInvoice.html fixed
- renamed next-button to check-in (checkInGuestOverview)
- renamed complete-button to check-out
> UI FIx Invoice + Button Confirm in Booking Summary 

- .idea/workspace.xml
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewBookingServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/LineItemTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/RoomTests.java
Tests for functions:
- findBookingById (including test for BookingNotFoundException)
- findTodaysCheckIns
- findTodaysCheckOuts
- moved LineItemTest to Domain-Test-Folder
- moved RoomTests to Domain-Test-Folder
all functions tested
> Tests: View Booking Service

- .idea/workspace.xml
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewBookingServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewGuestServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/LineItemTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/RoomTests.java
Tests for functions:
- findGuestById (including test for GuestNotFoundException)
all functions tested
> Tests: View Guest Service

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/GuestRepositoryImpl.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewBookingServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewGuestServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewRoomServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/LineItemTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/RoomTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/GuestRepositoryTests.java
Tests for function:
findRoomsByBookingId (including test for RoomNotFoundException)
> Tests: View Room Service

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/GuestRepositoryImpl.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewBookingServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewGuestServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewRoomServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/LineItemTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/domain/RoomTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/GuestRepositoryTests.java
Tests for functions:
- addGuest
- findGuestById
all functions tested
> Tests: Guest Repository

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/CheckInServiceImpl.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/CheckInServiceTest.java
> checkIn Service Test

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/ViewGuestServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/api/ViewGuestService.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/dto/GuestDTO.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/api/GuestRepository.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/GuestRepositoryImpl.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewGuestServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/GuestRepositoryTests.java
> findAllGuest

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/ViewBookingServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/api/ViewBookingService.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/api/BookingRepository.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/BookingRepositoryImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/GuestRepositoryImpl.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/ViewBookingServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/BookingRepositoryTests.java
> findAllBookings

- .idea/workspace.xml
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/HotelsoftwareApplication.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/Room.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/RoomRepositoryImpl.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/RoomRepositoryTests.java
Question: do i need to add a separate test for findRoomByBooking number? It's already getting tested in the persist test.
> added tests for room repository

- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingController.java
- hotelsoftware/src/main/resources/templates/createGuest.html
includes tasks:
- UI adjustment
- Search and insert with JavaScript
summary:
- createDummyData: more guests
- popup window design + implementation finished
- autofill for guests works
> use existing customer for booking user story finished

- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/CreateBookingServiceTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/CreateGuestServiceTests.java
tested function:
- createBooking 
all tests done
> Test: Create Booking Service

- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/BookingRepositoryImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/infrastructure/RoomRepositoryImpl.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/BookingRepositoryTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/RoomRepositoryTests.java
tested functions:
- findAllBookings()
- findBookingById()
- findTodaysCheckIns()
- findTodaysCheckOuts()
all tests created and run successfully
- findTodaysCheckIns returns now all bookings with status confirmed (no bookings with status pending anymore)
> Tests: Booking Repository

- hotelsoftware/src/main/resources/templates/bookingOverview.html
- hotelsoftware/src/main/resources/templates/bookingSummary.html
- hotelsoftware/src/main/resources/templates/checkInGuestOverview.html
- hotelsoftware/src/main/resources/templates/checkOutGuestOverview.html
- hotelsoftware/src/main/resources/templates/chooseRoom.html
- hotelsoftware/src/main/resources/templates/confirmSummary.html
- hotelsoftware/src/main/resources/templates/createGuest.html
- hotelsoftware/src/main/resources/templates/createInvoice.html
- hotelsoftware/src/main/resources/templates/dashboard.html
- hotelsoftware/src/main/resources/templates/errorPage.html
Added links to existing pages and highliting current page
> Links_to_all_pages

- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingController.java
- hotelsoftware/src/main/resources/static/priceCalculation.js
- hotelsoftware/src/main/resources/templates/bookingOverview.html
- hotelsoftware/src/main/resources/templates/bookingSummary.html
- hotelsoftware/src/main/resources/templates/checkInGuestOverview.html
- hotelsoftware/src/main/resources/templates/checkOutGuestOverview.html
- hotelsoftware/src/main/resources/templates/chooseRoom.html
- hotelsoftware/src/main/resources/templates/confirmSummary.html
- hotelsoftware/src/main/resources/templates/createGuest.html
- hotelsoftware/src/main/resources/templates/createInvoice.html
- hotelsoftware/src/main/resources/templates/errorPage.html
- hotelsoftware/src/main/resources/templates/invoiceSummary.html
- hotelsoftware/src/main/resources/templates/roomOverview.html
Added the function mentioned in title and fixed UI in choose room
> Automatic price calculation in choose room

- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/CheckInServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/api/CheckInService.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/exceptions/DoubleRoomNumberException.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/domain/model/exceptions/RoomCategoryMismatchException.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingController.java
- hotelsoftware/src/main/resources/templates/bookingSummary.html
- hotelsoftware/src/main/resources/templates/checkInGuestOverview.html
- hotelsoftware/src/main/resources/templates/checkOutGuestOverview.html
- hotelsoftware/src/main/resources/templates/chooseRoom.html
- hotelsoftware/src/main/resources/templates/confirmSummary.html
- hotelsoftware/src/main/resources/templates/createGuest.html
- hotelsoftware/src/main/resources/templates/createInvoice.html
- hotelsoftware/src/main/resources/templates/errorPage.html
- hotelsoftware/src/main/resources/templates/invoiceSummary.html
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/application/CheckInServiceTests.java
Possibility to change rooms at check-in:
write at checkInGuestOverview.html works
input validation and exception handling for all inputs (room numbers) at checkInGuestOverview
Wrote checkServiceTests for (RoomCategoryMismatchException, DoubleRoomNumberException)
UI adaptions:
removed border from readonly fields (checkInGuestOverview.html, checkOutGuestOverview.html, bookingSummary.html, confirmSummary.html)
added border between rows and cols (checkInGuestOverview.html, checkOutGuestOverview.html)
adapted headline sizes of all html pages
created new headlines for all html pages
adapted titles of all html pages
> Possibility to change rooms at check-in

- hotelsoftware/src/test/java/at/fhv/hotelsoftware/bdd/CheckInSzenario.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/bdd/SzenarioTxBoundary.java
@Transactional was not needed, but we needed to inherit from SzenarioTxBoundary which handles the transactions
> fixed szenario test

- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingController.java
- hotelsoftware/src/main/resources/templates/light.html
Controlling lights a hotel room
> Controlling Lights

- .idea/compiler.xml
- hotelsoftware/build.gradle
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/CreateBookingServiceImpl.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/api/CreateBookingService.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/dto/BookingDataDTO.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/BookingRestController.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/form/BookingForm.java
- hotelsoftware/src/main/java/at/fhv/hotelsoftware/view/form/GuestForm.java
- hotelsoftware/src/main/resources/static/frontend/src/components/CreateBookingComponent.js
- hotelsoftware/src/main/resources/templates/light.html
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/BookingRepositoryTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/GuestRepositoryTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/infrastructure/RoomRepositoryTests.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/view/RestApiTests.java
- All tests for rest-controller created and successful
- Found 6 old tests that failed -> now all (74) tests terminate successfully
- CreateBooking now returns a bookingId instead of void
- separate rest-api for guest creation and booking creation
> Rest Tests

- hotelsoftware/src/main/java/at/fhv/hotelsoftware/application/ViewRoomServiceImpl.java
- hotelsoftware/src/main/resources/static/frontend/package-lock.json
- hotelsoftware/src/main/resources/static/frontend/package.json
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/ApiClient.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/api/BookingRestControllerApi.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/index.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/model/BookingDataDTO.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/model/BookingForm.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/model/BookingId.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/model/GuestDTO.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/model/GuestId.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/model/RoomDTO.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/dist/model/RoomPriceDTO.js
- hotelsoftware/src/main/resources/static/frontend/src/components/api/package-lock.json
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/bdd/CheckInSzenario.java
- hotelsoftware/src/test/java/at/fhv/hotelsoftware/view/RestApiTests.java
- hotelsoftware/src/test/resources/features/CheckIn.feature
Integration Test fixed (failed because there are by default no rooms in the database)
Adapted REST Tests
> Integration Test fix + REST Tests fix
